-- Week 4 Day 2: Snowflake SQL transfer drill solutions
USE WAREHOUSE <INSTRUCTOR_WAREHOUSE>;
USE DATABASE SNOWFLAKE_SAMPLE_DATA;
USE SCHEMA TPCH_SF1;

-- DRILL 1: Customers from one nation
SELECT
  C_CUSTKEY,
  C_NAME,
  C_ADDRESS,
  C_NATIONKEY
FROM CUSTOMER
WHERE C_NATIONKEY = 3
ORDER BY C_NAME
LIMIT 20;

-- DRILL 2: Suppliers with strong account balances
SELECT
  S_SUPPKEY,
  S_NAME,
  S_ACCTBAL
FROM SUPPLIER
WHERE S_ACCTBAL > 5000
ORDER BY S_ACCTBAL DESC
LIMIT 20;

-- DRILL 3: Categorize part sizes
SELECT
  P_PARTKEY,
  P_NAME,
  P_SIZE,
  CASE
    WHEN P_SIZE <= 20 THEN 'SMALL'
    ELSE 'LARGE'
  END AS SIZE_BAND
FROM PART
ORDER BY P_PARTKEY
LIMIT 50;

-- DRILL 4: Order count by year
SELECT
  DATE_TRUNC('YEAR', O_ORDERDATE) AS ORDER_YEAR,
  COUNT(*) AS ORDER_COUNT
FROM ORDERS
GROUP BY DATE_TRUNC('YEAR', O_ORDERDATE)
ORDER BY ORDER_YEAR;

-- DRILL 5: Order status summary
SELECT
  O_ORDERSTATUS,
  COUNT(*) AS ORDER_COUNT,
  ROUND(AVG(O_TOTALPRICE), 2) AS AVG_ORDER_TOTAL,
  ROUND(SUM(O_TOTALPRICE), 2) AS TOTAL_ORDER_VALUE
FROM ORDERS
GROUP BY O_ORDERSTATUS
ORDER BY ORDER_COUNT DESC;

-- DRILL 6: High-volume order clerks
SELECT
  O_CLERK,
  COUNT(*) AS ORDER_COUNT,
  ROUND(SUM(O_TOTALPRICE), 2) AS TOTAL_ORDER_VALUE
FROM ORDERS
GROUP BY O_CLERK
HAVING COUNT(*) >= 1500
ORDER BY TOTAL_ORDER_VALUE DESC;

-- DRILL 7: German customer directory
SELECT
  c.C_CUSTKEY,
  c.C_NAME,
  n.N_NAME
FROM CUSTOMER AS c
JOIN NATION AS n
  ON c.C_NATIONKEY = n.N_NATIONKEY
WHERE n.N_NAME = 'GERMANY'
ORDER BY c.C_NAME
LIMIT 25;

-- DRILL 8: Market segment order performance
SELECT
  c.C_MKTSEGMENT,
  COUNT(DISTINCT c.C_CUSTKEY) AS CUSTOMER_COUNT,
  COUNT(*) AS ORDER_COUNT,
  ROUND(AVG(o.O_TOTALPRICE), 2) AS AVG_ORDER_TOTAL,
  ROUND(SUM(o.O_TOTALPRICE), 2) AS TOTAL_ORDER_VALUE
FROM CUSTOMER AS c
JOIN ORDERS AS o
  ON c.C_CUSTKEY = o.O_CUSTKEY
GROUP BY c.C_MKTSEGMENT
ORDER BY TOTAL_ORDER_VALUE DESC;

-- DRILL 9: Supplier count by region
SELECT
  r.R_NAME,
  COUNT(DISTINCT s.S_SUPPKEY) AS SUPPLIER_COUNT
FROM REGION AS r
JOIN NATION AS n
  ON r.R_REGIONKEY = n.N_REGIONKEY
JOIN SUPPLIER AS s
  ON n.N_NATIONKEY = s.S_NATIONKEY
GROUP BY r.R_NAME
ORDER BY SUPPLIER_COUNT DESC;

-- DRILL 10: Top German customers
SELECT
  c.C_CUSTKEY,
  c.C_NAME,
  COUNT(*) AS ORDER_COUNT,
  ROUND(SUM(o.O_TOTALPRICE), 2) AS TOTAL_ORDER_VALUE
FROM CUSTOMER AS c
JOIN ORDERS AS o
  ON c.C_CUSTKEY = o.O_CUSTKEY
JOIN NATION AS n
  ON c.C_NATIONKEY = n.N_NATIONKEY
WHERE n.N_NAME = 'GERMANY'
GROUP BY c.C_CUSTKEY, c.C_NAME
ORDER BY TOTAL_ORDER_VALUE DESC
LIMIT 5;

-- DRILL 11: Parts supplied from Europe
SELECT DISTINCT
  p.P_PARTKEY,
  p.P_NAME,
  s.S_SUPPKEY,
  s.S_NAME,
  n.N_NAME
FROM PART AS p
JOIN PARTSUPP AS ps
  ON p.P_PARTKEY = ps.PS_PARTKEY
JOIN SUPPLIER AS s
  ON ps.PS_SUPPKEY = s.S_SUPPKEY
JOIN NATION AS n
  ON s.S_NATIONKEY = n.N_NATIONKEY
JOIN REGION AS r
  ON n.N_REGIONKEY = r.R_REGIONKEY
WHERE r.R_NAME = 'EUROPE'
ORDER BY p.P_PARTKEY, s.S_SUPPKEY
LIMIT 50;

-- DRILL 12: Orders containing part 5
SELECT DISTINCT
  c.C_CUSTKEY,
  c.C_NAME,
  o.O_ORDERKEY,
  o.O_ORDERDATE,
  o.O_TOTALPRICE
FROM CUSTOMER AS c
JOIN ORDERS AS o
  ON c.C_CUSTKEY = o.O_CUSTKEY
JOIN LINEITEM AS l
  ON o.O_ORDERKEY = l.L_ORDERKEY
WHERE l.L_PARTKEY = 5
ORDER BY o.O_ORDERDATE, o.O_ORDERKEY;

-- DRILL 13: Delayed shipment lines
SELECT
  o.O_ORDERKEY,
  l.L_LINENUMBER,
  o.O_ORDERDATE,
  l.L_SHIPDATE,
  DATEDIFF('DAY', o.O_ORDERDATE, l.L_SHIPDATE) AS DAYS_TO_SHIP
FROM ORDERS AS o
JOIN LINEITEM AS l
  ON o.O_ORDERKEY = l.L_ORDERKEY
WHERE DATEDIFF('DAY', o.O_ORDERDATE, l.L_SHIPDATE) > 30
ORDER BY DAYS_TO_SHIP DESC, o.O_ORDERKEY
LIMIT 50;

-- DRILL 14: Orders with many line items
SELECT
  L_ORDERKEY,
  COUNT(*) AS LINE_ITEM_COUNT,
  ROUND(SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)), 2) AS DISCOUNTED_REVENUE
FROM LINEITEM
GROUP BY L_ORDERKEY
HAVING COUNT(*) >= 5
ORDER BY LINE_ITEM_COUNT DESC, DISCOUNTED_REVENUE DESC
LIMIT 50;

-- DRILL 15: Top suppliers by discounted revenue
SELECT
  s.S_SUPPKEY,
  s.S_NAME,
  COUNT(*) AS LINE_ITEM_COUNT,
  ROUND(SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)), 2) AS DISCOUNTED_REVENUE
FROM SUPPLIER AS s
JOIN LINEITEM AS l
  ON s.S_SUPPKEY = l.L_SUPPKEY
GROUP BY s.S_SUPPKEY, s.S_NAME
ORDER BY DISCOUNTED_REVENUE DESC
LIMIT 5;
