-- Week 4 Day 3 GTFS provided setup
-- GoogleSQL for BigQuery.
-- Copy this file to student-work/week4/day3/gtfs_setup.sql.
-- This file uses temporary tables, so nothing permanent is created.
-- Before running: enable BigQuery session mode in Query settings.
-- Keep this setup and every warm-up query in the same query editor tab.
-- Run it before the separate gtfs_warmup.sql starter. Do not edit this file.

-- ---------------------------------------------------------------------------
-- PROVIDED SETUP: Tiny GTFS-inspired sample data
-- Run this section. Do not count it as completed student work.
-- ---------------------------------------------------------------------------

SELECT @@session_id AS session_id;

CREATE OR REPLACE TEMP TABLE routes AS
SELECT
  route_id,
  route_short_name,
  route_long_name,
  route_type
FROM UNNEST([
  STRUCT('R10' AS route_id, '10' AS route_short_name, 'Downtown Loop' AS route_long_name, 3 AS route_type),
  STRUCT('R20' AS route_id, '20' AS route_short_name, 'Airport Express' AS route_long_name, 3 AS route_type),
  STRUCT('R30' AS route_id, '30' AS route_short_name, 'University Connector' AS route_long_name, 3 AS route_type)
]);

CREATE OR REPLACE TEMP TABLE trips AS
SELECT
  trip_id,
  route_id,
  service_id,
  trip_headsign
FROM UNNEST([
  STRUCT('T100' AS trip_id, 'R10' AS route_id, 'weekday' AS service_id, 'Downtown clockwise' AS trip_headsign),
  STRUCT('T101' AS trip_id, 'R10' AS route_id, 'weekday' AS service_id, 'Downtown counterclockwise' AS trip_headsign),
  STRUCT('T200' AS trip_id, 'R20' AS route_id, 'weekday' AS service_id, 'Airport terminal' AS trip_headsign),
  STRUCT('T201' AS trip_id, 'R20' AS route_id, 'weekend' AS service_id, 'Airport terminal' AS trip_headsign),
  STRUCT('T300' AS trip_id, 'R30' AS route_id, 'weekday' AS service_id, 'University campus' AS trip_headsign)
]);

CREATE OR REPLACE TEMP TABLE stop_times AS
SELECT
  trip_id,
  stop_sequence,
  arrival_time,
  stop_id
FROM UNNEST([
  STRUCT('T100' AS trip_id, 1 AS stop_sequence, '08:00:00' AS arrival_time, 'S1' AS stop_id),
  STRUCT('T100' AS trip_id, 2 AS stop_sequence, '08:10:00' AS arrival_time, 'S2' AS stop_id),
  STRUCT('T100' AS trip_id, 3 AS stop_sequence, '08:20:00' AS arrival_time, 'S3' AS stop_id),
  STRUCT('T101' AS trip_id, 1 AS stop_sequence, '09:00:00' AS arrival_time, 'S3' AS stop_id),
  STRUCT('T101' AS trip_id, 2 AS stop_sequence, '09:12:00' AS arrival_time, 'S2' AS stop_id),
  STRUCT('T101' AS trip_id, 3 AS stop_sequence, '09:24:00' AS arrival_time, 'S1' AS stop_id),
  STRUCT('T200' AS trip_id, 1 AS stop_sequence, '06:30:00' AS arrival_time, 'S4' AS stop_id),
  STRUCT('T200' AS trip_id, 2 AS stop_sequence, '06:55:00' AS arrival_time, 'S5' AS stop_id),
  STRUCT('T201' AS trip_id, 1 AS stop_sequence, '10:30:00' AS arrival_time, 'S4' AS stop_id),
  STRUCT('T201' AS trip_id, 2 AS stop_sequence, '10:58:00' AS arrival_time, 'S5' AS stop_id),
  STRUCT('T300' AS trip_id, 1 AS stop_sequence, '07:45:00' AS arrival_time, 'S6' AS stop_id),
  STRUCT('T300' AS trip_id, 2 AS stop_sequence, '08:05:00' AS arrival_time, 'S7' AS stop_id),
  STRUCT('T300' AS trip_id, 3 AS stop_sequence, '08:25:00' AS arrival_time, 'S8' AS stop_id),
  STRUCT('T300' AS trip_id, 4 AS stop_sequence, '08:45:00' AS arrival_time, 'S9' AS stop_id)
]);

-- Preview the tables.
SELECT route_id, route_short_name, route_long_name, route_type FROM _SESSION.routes ORDER BY route_short_name;
SELECT trip_id, route_id, service_id, trip_headsign FROM _SESSION.trips ORDER BY route_id, trip_id;
SELECT trip_id, stop_sequence, arrival_time, stop_id FROM _SESSION.stop_times ORDER BY trip_id, stop_sequence;

-- Setup complete. Write the six answers in gtfs_warmup.sql.
